---
- name: Kiszolgáló oldali beállítások és telepítés
  hosts: "{{ server }}"
  vars_files:
    - config.yml
  tasks:
    - name: Rendszer felhasználó hozzáadása 
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/bash
        append: yes
    - name: Samba konfiguráció és telepítés
      ansible.builtin.import_role:
        name: vladgh.samba.server
      vars:
        samba_users:
        - name: "{{ user }}"
          password: "{{ smb_password }}"
        samba_shares:
        - name: "{{ share_name }}"
          group: "{{ user }}" 
          write_list: "{{ user }}"
        samba_shares_root: /data
    - name: Tűzfal zóna létrehozása
      ansible.posix.firewalld:
        zone: custom
        permanent: true
        state: present
    - name: Szolgáltatások engedélyezése
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: yes
      loop:
        - samba
        - ssh
    - name: Port engedélyezése
      firewalld:
        port: 4312/tcp
        state: enabled
        permanent: true
        immediate: yes

- name: Kilensoldali beállítások és telepítés
  hosts: "{{ client }}"
  vars_files:
    - config.yml
  tasks:
    - name: Könyvtár létrehozása
      ansible.builtin.file:
        path: "{{ mount_path }}"
        state: directory
        mode: '0777'
    - name: cifs-utils telepítése
      ansible.builtin.dnf:
        name: cifs-utils
        state: present
      notify: Felcsatolás fstab-al
  handlers:
    - name: Felcsatolás fstab-al
      ansible.posix.mount:
        src: "{{ '//' + server + '/' + share_name }}"
        path: "{{ mount_path }}"
        opts: "{{ 'user=' + user + ',password=' + smb_password }}"  
        state: mounted
        fstype: cifs

