---
- name: Install and start Apache HTTPD
  hosts: servera
  tasks:
    - name: A normal task
      ansible.builtin.debug:
        msg: 'first task'
    - name: SMB install and config
      ansible.builtin.import_role:
        name: ma_sch.samba
