---
#- name: Fact dump
#  hosts: servera
#  tasks:
#    - name: Print all facts
#      ansible.builtin.debug:
#        var: ansible_facts
- name: Install and configures SAMBA shares
  hosts: servera
  tasks:
    - name: Ensure group "pirate" exists
      ansible.builtin.group:
        name: pirate
        state: present
    - name: Add system user 
      ansible.builtin.user:
        name: alice
        groups: pirate
        shell: /bin/bash
        append: yes
    - name: SMB install and config
      ansible.builtin.import_role:
        name: vladgh.samba.server
      vars:
        samba_users:
        - name: alice
          password: ecila
        samba_shares:
        - name: pirate
          group: pirate 
          write_list: +pirate
    - name: permit traffic in default zone for smb service
      ansible.posix.firewalld:
        service: samba
        permanent: true
        state: enabled

# OK tüzfalon smb engedélyezése
# OK írás próba        
# handler: felcsatolás fstabbal

# csak elsődleges főnök group-al mi történik?
