---
- name: Install and configure SAMBA shares on the server
  hosts: "{{ server }}"
  vars_files:
    - vars/config.yml
  tasks:
    - name: Add system user 
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/bash
        append: yes
    - name: SMB install and config
      ansible.builtin.import_role:
        name: vladgh.samba.server
      vars:
        samba_users:
        - name: "{{ user }}"
          password: "{{ smb_password }}"
        samba_shares:
        - name: "{{ share_name }}"
          group: "{{ user }}" 
          write_list: "{{ user }}"
        samba_shares_root: /data
    - name: Set firewalld
      ansible.posix.firewalld:
        service: samba
        permanent: true
        state: enabled
        immediate: yes

- name: mount SAMBA share on the client
  hosts: "{{ client }}"
  vars_files:
    - vars/config.yml
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ mount_path }}"
        state: directory
        mode: '0777'
    - name: Install cifs-utils
      ansible.builtin.dnf:
        name: cifs-utils
        state: present
    - name: Make fstab entry and mount
      ansible.posix.mount:
        src: "{{ '//' + server + '/' + share_name }}"
        path: "{{ mount_path }}"
        opts: "{{ 'user=' + user + ',password=' + smb_password }}"  
        state: mounted
        fstype: cifs

