---
#- name: Fact dump
#  hosts: servera
#  tasks:
#    - name: Print all facts
#      ansible.builtin.debug:
#        var: ansible_facts
- name: Install and configures SAMBA shares
  hosts: servera
  tasks:
    - name: Add system users 
      ansible.builtin.user:
        name: alice
        groups: root
        shell: /bin/bash
        append: yes
    - name: SMB install and config
      ansible.builtin.import_role:
        name: vladgh.samba.server
      vars:
        samba_users:
        - name: alice
          password: ecila
        samba_shares:
        - name: pirate
          group: root 
        
# telepítés role-al
# system user létrehozás
# könyvtár létrehozás
# samba user létrehozás
# samba share létrehozás
# selinux szabályok alkalmazása
# handler: felcsatolás fstabbal
