---
- name: Install and configures SAMBA shares
  hosts: servera
  tasks:
    - name: Ensure group "pirate" exists
      ansible.builtin.group:
        name: pirate
        state: present
    - name: Add system user 
      ansible.builtin.user:
        name: alice
        groups: pirate
        shell: /bin/bash
        append: yes
    - name: SMB install and config
      ansible.builtin.import_role:
        name: vladgh.samba.server
      vars:
        samba_users:
        - name: alice
          password: ecila
        samba_shares:
        - name: pirate
          group: pirate 
          write_list: +pirate
    - name: Set firewalld
      ansible.posix.firewalld:
        service: samba
        permanent: true
        state: enabled
        immediate: yes

- name: mount SAMBA share
  hosts: serverb
  tasks:
    - name: Install cifs-utils
      ansible.builtin.dnf:
        name: cifs-utils
        state: present
    - name: Make fstab entry and mount
      ansible.posix.mount:
        src: //servera/pirate
        path: /mnt
        opts: user=alice,password=ecila
        state: mounted
        fstype: cifs

